default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["PG_USERNAME"] || "postgres" %>
  password: <%= ENV["PG_PASSWORD"] || "root" %>
  host: <%= ENV["PG_HOST"] || "localhost" %>
  port: <%= ENV["PG_PORT"] || 5432 %>

development:
  <<: *default
  database: pizza_factory_development

test:
  <<: *default
  database: pizza_factory_test

production:
  <<: *default
  database: pizza_factory_production
  username: <%= ENV["PG_USERNAME"] || "your_production_username" %>
  password: <%= ENV["PG_PASSWORD"] || "your_production_password" %>
  host: <%= ENV["PG_HOST"] || "your_production_host" %>
